apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    # kubernetes.io/ingress.class: "nginx"
  name: gohttpserver
spec:
  rules:
  - host: localhost.test
    http:
      paths:
      - path: /http(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: gohttpserver
            port:
              name: http
  tls:
  - hosts:
      - localhost.test
    # secretName: tls-secret

# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#     kubernetes.io/ingress.class: "nginx"
#   name: gohttpserver
# spec:
#   rules:
#   - host: localhost.test
#     http:
#       paths:
#       - path: /http(/|$)(.*)
#         backend:
#           serviceName: gohttpserver
#           servicePort: http
#   tls:
#   - hosts:
#       - localhost.test
#     secretName: tls-secret
