apiVersion: v1
kind: Service
metadata:
  name: goingserver
  labels:
    app.kubernetes.io/name: goingserver
spec:
  selector:
    app.kubernetes.io/name: goingserver
  ports:
    - name: grpc
      port: 30111
      targetPort: grpc

# apiVersion: v1
# kind: Service
# metadata:
#   name: goingserver
#   labels:
#     app.kubernetes.io/name: goingserver
# spec:
#   selector:
#     app.kubernetes.io/name: goingserver
#   ports:
#     - name: grpc
#       port: 30111
#       targetPort: grpc
